#!/usr/bin/env bash
# Displays "Best School" 10 times using a while loop.
#   On the 9th iteration, displays "Hi" before "Best School".

#!/bin/bash

count=1

while [ $count -le 10 ]
do
    if [ $count -eq 9 ]; then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    ((count++))
done

